### PR TITLE
Feature/bookmark enhancements

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
Sigh please check now
why the heck I keep sending PR to wrong branches 😢

### CODE REVIEW

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
css line 558, can u pls add it in seperate `.svg` file

**Comment by Thunder-Blaze** [comment]
sure, and btw I found the way to make icon size bigger so I will do that too and push it

**Comment by Thunder-Blaze** [comment]
@prem-k-r @itz-rj-here you guys can check when you are free
I think it's almost done, also increased the favicon size and made the bookmarks load only on clicking the right arrow or pressing right arrow key

**Comment by itz-rj-here** [comment]
@prem-k-r can you confirm the changes for me. As im on my phone 😅.

**Comment by prem-k-r** [comment]
> @prem-k-r can you confirm the changes for me. As im on my phone 😅.

Me too lol

**Comment by prem-k-r** [comment]
There is a conflict.. probably favicon link.. it's a quick fix

**Comment by itz-rj-here** [comment]
> There is a conflict.. probably favicon link.. it's a quick fix

From phone how?

**Comment by itz-rj-here** [comment]
@prem-k-r just mention me if it works properly. Im going for now. Have to do my dinner 🙃.

**Comment by Thunder-Blaze** [comment]
aah wait ig

**Comment by Thunder-Blaze** [comment]
hmm, still having minor CSS errors in firefox

**Comment by Thunder-Blaze** [comment]
image
@prem-k-r umm u removed the default folders of brave and edge

**Comment by prem-k-r** [comment]
Ah sorry, might have happened when fixing conflicts and all.. 
Can you please add them back

**Comment by Thunder-Blaze** [comment]
@prem-k-r no worries, I added them back

**Comment by Thunder-Blaze** [comment]
I think it is working for me in Edge, Firefox, Chrome and Brave
but I am somehow very bad at testing so merge after testing on your PCs :)

**Comment by prem-k-r** [comment]
Thanks.. Is there any issue left other than no favicon error? 
Anything not expected happening in firefox?

**Comment by Thunder-Blaze** [comment]
I don't think there should be any errors except favicon imo but lets see after you guys have tested :)

**Comment by itz-rj-here** [comment]
Great. Now it works properly. Also the codes are fine. Before you fix the api's it wasn't working properly. :)

**Review by itz-rj-here — APPROVED** [review]

**Pull request merged**
