### PR TITLE
bookmark update

### PR DESCRIPTION
**Pull request by prem-k-r**
Clickable Nameless Bookmarks
Ctrl+Click to Open in a New Tab
Search by URL
and some +

### CODE REVIEW

**Comment by prem-k-r** [comment]
@itz-rj-here please review

**Comment by itz-rj-here** [comment]
Bruh i just came home. 🗿
Give me 5-6 mins.

**Comment by prem-k-r** [comment]
> Bruh i just came home. 🗿 Give me 5-6 mins.

no hurry :)

**Comment by prem-k-r** [comment]
sorry reverted back icon.. unnecessary size inc

**Comment by itz-rj-here** [comment]
@prem-k-r it's ready now?

**Pull request merged**
