### PR TITLE
Enhanced Bookmarks UI

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
- Enhanced UI
- Made the names more Specific
- Modified some Event Listener Functions

### CODE REVIEW

**Comment by itz-rj-here** [comment]
What the heck?
I didn't got any notification for this pr... lol
odd.

**Comment by Thunder-Blaze** [comment]
lol np

**Comment by Thunder-Blaze** [comment]
You can merge it and then add the brave specific condition

**Comment by itz-rj-here** [comment]
> You can merge it and then add the brave specific condition

Okaye. As you suggest.

**Pull request merged**
