### PR TITLE
Feature/bookmark enhancements

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
Will add toggle at night
You can review and merge

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
@Thunder-Blaze The code looked fine to me. So i merged it then saw that im getting some issue with selecting grid and list.
image

You should double check your code and also test your code by your own for more clearification.

**Comment by itz-rj-here** [comment]
I can't select the grid or list button also the search icon is placed wrong.

**Comment by Thunder-Blaze** [comment]
hmm the toggle was not yet made that's why you couldn't switch
I'll recheck the search icon position
And ik what's causing the weird placement in secrets folder, gimme a min

**Comment by Thunder-Blaze** [comment]
btw which browser is that, search seems to be fine for me in brave and chrome

**Comment by itz-rj-here** [comment]
Seriously?
I'm using chrome anyways...

**Pull request merged**
