### PR TITLE
Update for Firefox

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by prem-k-r** [comment]
@itz-rj-here can you please check if it's working on firefox

**Comment by itz-rj-here** [comment]
@prem-k-r it doesn't shows up the permission request. Also not showing the bookmarks.
image

**Comment by prem-k-r** [comment]
permission request wont show for firefox.. they still use manifest v2.. there is no optional permission

letme recheck the code

**Comment by prem-k-r** [comment]
btw, I hope you reloaded the extension as manifest is updated

**Comment by itz-rj-here** [comment]
> btw, I hope you reloaded the extension as manifest is updated

Yup. I double checked it.

**Comment by itz-rj-here** [comment]
> btw, I hope you reloaded the extension as manifest is updated

I also downloaded your files changes to check it separately :)

**Comment by prem-k-r** [comment]
ok, actually i am not copy-pasting whole file.. its is messed up

**Comment by itz-rj-here** [comment]
@prem-k-r i reverted the pr. Can you change the code please.

**Comment by prem-k-r** [comment]
actually that was not completed

**Comment by prem-k-r** [comment]
@itz-rj-here please check now

**Comment by itz-rj-here** [comment]
image
Well. Using this method it doesn't asks for the bookmark permission. But as we don't have any other option left we can go with it.

image
The delete button doesn't work properly... @prem-k-r

**Comment by prem-k-r** [comment]
@itz-rj-here please check now

**Comment by itz-rj-here** [comment]
> @itz-rj-here please check now

Can you fix the conflicts first 😅

**Comment by prem-k-r** [comment]
> > @itz-rj-here please check now
> 
> Can you fix the conflicts first 😅

done

**Comment by prem-k-r** [comment]
too many commits :(
Smash it

**Comment by itz-rj-here** [comment]
If you can confirm me that the codes are correct and perfectly works on firefox and chrome then i can merge the pr from my phone. :)

**Comment by prem-k-r** [comment]
Is working fine for me... If last last time u checked, except delete button not working.. rest were fine.. then we are good to go

**Review by itz-rj-here — APPROVED** [review]
The code also looks fine to me from the phone. 🙂

**Pull request merged**
